//Java入门
//public class Hello 表示Hello是一个类，是一个public（公有）的类
//Hello{ } 表示一个类的开始和结束
//public static void main(String[] args) 表示一个主方法，即我们程序的入口
//main(){}表示方法的开始和结束
//System.out.println("hello,world"); 表示输出"hello,world"
public class Hello{
	//编写一个main方法
	public static void main(String[] args){
		System.out.println("hello,world");
	}
}

class Dog{
	public static void main(String[] args){
		System.out.println("hello~dog");
	}
}

class Tiger{
	public static void main(String[] args){
		System.out.println("hello~tiger");
	}
}